#! /usr/bin/env bash

: "${ircdir:=$HOME/backtick/ii-fifos}"
: "${botdir:=$HOME/backtick}"
: "${nickname:=\`}"

if pgrep "ii" > /dev/null
then
    killall ii
    sleep 5
fi

network="irc.foonetic.net"
channels=(
    '#test'
    '#builds'
)


# some privacy please, thanks
chmod 700 "$ircdir"
chmod 600 "$ircdir"/*/ident &>/dev/null

monitor() {
    tail -F -n0 --pid=$1 "$ircdir/$network/$channel/out" | \
        while read -r date time nick 'msg'; do
            # if msg is by the system ignore it
            [[ "$nick" == '-!-' ]] && continue
            # strip < and >. if msg is by ourself ignore it
            nick="${nick:1:-1}"
            [[ "$nick" == "$nickname" ]] && continue

            # if msg contains a url, transform to url command
            [[ "$msg" =~ https?:// ]] && \
                exec ./iicmd "$nick" "url ${msg#* }" "$botdir" "$network" "$channel" "$nickname" | fold -w 255 &
            # if msg is a command, invoke iicmd
            if echo "$msg" | grep -q '^`.*`$'; then
                msg=${msg%\`}
                exec ./iicmd "$nick" "$msg" "$botdir" "$network" "$channel" "$nickname" | fold -w 255 &
            fi
        done > "$ircdir/$network/$channel/in"
}

mc-chat() {
    tail -F -n0 --pid=$1 "$botdir/mc-logs/chat.txt" | \
        while read -r date time nick 'msg'; do
            [[ $msg == \`* ]] && printf -- "%s %s \n" "$nick" "${msg#\`}"
        done > "$ircdir/$network/$channel/in"
}
mc-connect() {
    tail -F -n0 --pid=$1 "$botdir/mc-logs/connections.txt" | \
        while read -r date time nick status ip; do
            printf -- "%s %s the server.\n" "$nick" "${status%\.}"
        done > "$ircdir/$network/$channel/in"
}

# cleanup
rm -f "$ircdir/$network/in"

# connect to network - password is set through the env var IIPASS
ii -i "$ircdir" -n "$nickname" -u "lhk-bot" -f "backtick" -k IIPASS -s "$network" &
iid="$!"

# wait for the connection
while ! test -p "$ircdir/$network/in"; do sleep 1; done

# auth to services
[[ -e "$ircdir/$network/ident" ]] && \
    printf -- "/j nickserv identify %s\n" "$(<"$ircdir/$network/ident")" > "$ircdir/$network/in"
rm -f "$ircdir/$network/nickserv/out" # clean that up - ident passwd is in there

# join channels
for channel in ${channels[@]}; do
    printf -- "/j %s\n" "$channel" > "$ircdir/$network/in"
    monitor $iid &
    pids+=($!)
done

channel="#builds"
mc-chat $iid &
pids+=($!)

channel="#test"
mc-connect $iid &
pids+=($!)
