#! /usr/bin/env bash

: "${ircdir:=$HOME/backtick/ii-fifos}"
: "${botdir:=$HOME/backtick}"
: "${nickname:=\`}"

export ircdir botdir nickname

if pgrep "ii" > /dev/null
then
    killall ii
    sleep 5
fi

[[ -v networks ]] || declare -A networks=(
    [irc.foonetic.net]="#test #イヴの時間"
)

# some privacy please, thanks
chmod 700 "$ircdir"
chmod 600 "$ircdir"/*/ident &>/dev/null

monitor() {
    echo $ircdir $network $channel
    tail -F -n0 --pid=$1 "$ircdir/$network/$channel/out" | \
        while read -r date time source 'msg'; do
            # if msg is by the system ignore it
            [[ "$source" == '-!-' ]] && continue
            # strip < and >. if msg is by ourself ignore it
            source="${nick:1:-1}"
            [[ "$source" == "$nickname" ]] && continue

            # if msg contains a url, transform to url command
            [[ "$msg" =~ https?:// ]] && \
                exec ./iicmd "$source" "url ${msg#* }" "$botdir" "$network" "$channel" | fold -w 255 &
            # if msg is a command, invoke iicmd
            if [[ "$msg" =~ ^'`'(.*)'`'$ || "$msg" =~ ^'$('(.*)')'$ ]] ; then
                msg=${BASH_REMATCH[1]}
                exec ./iicmd "$source" "$msg" "$botdir" "$network" "$channel" | fold -w 255 &
            fi
        done > "$ircdir/$network/$channel/in"
}

mc-chat() {
    tail -F -n0 --pid=$1 "$botdir/mc-logs/chat.txt" | \
        while read -r date time nick 'msg'; do
            [[ $msg == \`* ]] && printf -- "%s %s \n" "$nick" "${msg#\`}"
        done > "$ircdir/$network/$channel/in"
}
mc-connect() {
    tail -F -n0 --pid=$1 "$botdir/mc-logs/connections.txt" | \
        while read -r date time nick status ip; do
            printf -- "%s %s the server.\n" "$nick" "${status%\.}"
        done > "$ircdir/$network/$channel/in"
}

for network in ${!networks[@]} ; do
    # cleanup
    rm -f "$ircdir/$network/in"

    # connect to network - password is set through the env var IIPASS
    ii -i "$ircdir" -n "$nickname" -u "lhk-bot" -f "backtick" -k IIPASS -s "$network" &
    iid="$!"

    # wait for the connection
    while ! test -p "$ircdir/$network/in"; do sleep 1; done

    # auth to services
    [[ -e "$ircdir/$network/ident" ]] && \
        printf -- "/j nickserv identify %s\n" "$(<"$ircdir/$network/ident")" > "$ircdir/$network/in"
    rm -f "$ircdir/$network/nickserv/out" # clean that up - ident passwd is in there

    # join channels
    for channel in ${networks[$network]} ; do
        echo "chng" $channel
        printf -- "/j %s\n" "$channel" > "$ircdir/$network/in"
        monitor $iid &
        pids+=($!)
    done
done

#channel="#builds"
#mc-chat $iid &
#pids+=($!)
#
#channel="#test"
#mc-connect $iid &
#pids+=($!)
